### ISSUE TITLE
Make a flake linter file and enable travis

### ISSUE THREAD

**Issue by amishas157** [amishas157/osm-fudge#10]
My sublime editor behaves little weirdly and enters spaces and tabs. Need to get a linter file and enable travis repo in this repo so that lint check happens for every commit push

![image](https://user-images.githubusercontent.com/4952872/41182291-9fd386fa-6b92-11e8-8d03-9e108d1fdbe6.png)

**Comment by amishas157** [comment]
Enabled in https://github.com/amishas157/osm-fudge/pull/6/commits/5028c18fc4d8b01472cb29dab13c9c50a2aeeca7 and https://github.com/amishas157/osm-fudge/pull/6/commits/b923c3c044f564071623cb791b4cd32ff13e2e70

**Comment by daniel-j-h** [comment]
Nice! You could also add the travis badge to the readme know, so it's official :D
